apiVersion: v1
kind: pod
metadata:
  name: sample-pod
spec:
  imagePullPolicy: Always
  containers:
    - name: demo
      image: 673904956414.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-store:latest
