apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-ssm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::673904956414:role/oidc-test

---
apiVersion: v1
kind: pod
metadata:
  name: sample-pod
spec:
  serviceAccountName: oidc-ssm
  imagePullPolicy: Always
  containers:
    - name: demo
      image: 673904956414.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-store:latest
      env:
        - name: PARAMS
          value: "prod.payment.cart_port prod.payment.user_port prod.payment.cart_host"